# Generated by Django 5.2.4 on 2025-07-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
